version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/ilumeo
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
      npx prisma generate &&
      npm run start:dev
      "

  db:
    image: postgres:14-alpine
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ilumeo
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
